apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : myapi
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: myapi
  source:
    path   : "helm/myapi"
    repoURL: "git@github.com:MisyuraIlya/argo-app.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: "container.image"
        value: spetsar/myapi:latest

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    